### ISSUE TITLE
tooling to easily see generated contract code

### ISSUE THREAD

**Issue by snd** [paritytech/sol-rs#15]
writing tests in rust with sol-rs involves dealing with a lot of generated code (generated by ethabi-derive). that code is  difficult to "imagine". i found it very helpful to see the generated code.

it would be great to have something like a cargo command to easily generate the ethabi rust code from a solidity file.

here are two examples of generated code:

validators: textup.fr/231979a6

foreign bridge: https://gist.github.com/snd/8dad886c6acdf057a18e2c29b6255c48

**Comment by snd** [comment]
ethabi itself might be a good place for this

**Comment by lght** [comment]
> that code is difficult to "imagine". i found it very helpful to see the generated code.

agreed, while we're still dealing with generated code from ethabi, seeing the actual code is crucial for debugging. don't know what the roadmap looks like for removing/replacing generated code in ethabi.

**Comment by snd** [comment]
so far i've used https://github.com/dtolnay/cargo-expand to achieve this.
still requires some manual setup though.

something like `cargo ethabi-derive path-to-solidity-file.sol > path-to-generated-rust.rs` would be great

**Comment by lght** [comment]
> something like cargo ethabi-derive path-to-solidity-file.sol > path-to-generated-rust.rs would be great

absolutely, not sure how to tie into the cargo scripting system to achieve that.

**Comment by snd** [comment]
`cargo doc` creates documentation for the module generated by `use_contract!`. imho that's a great way to browse that module for now

**Comment by snd** [comment]
i'm now using the following solution:

for a project using `ethabi-derive` have the contracts in a seperate crate (in the workspace) that only contains the contracts. example https://github.com/paritytech/parity-bridge/tree/9dfa37f02a462947da85f23a422e55109a4904d8/contracts

run `cargo doc` within that crate's directory. voila documentation of derived contracts.

closing this as i no longer think there needs to be additional tooling for this
