### ISSUE TITLE
improving sol::unit

### ISSUE THREAD

**Issue by snd** [paritytech/sol-rs#17]
there are some unit conversion functions in `sol::unit`: https://github.com/paritytech/sol-rs/blob/aed4bb377db6bf7459e5ee3792e1d7cddfb45cef/solaris/src/unit.rs

i have some thoughts on improving them:

- support all units supported by web3 js https://github.com/ethereum/wiki/wiki/JavaScript-API#web3towei
- make it clearer that the functions convert to wei
  - right now they are just called  `ether`, `shannon`, etc
  - maybe call them `ether_to_wei`, etc
- don't assume `usize` as argument type to the functions
  - either just directly take `U256` or take `T: Into<U256>`
- move `convert` function somewhere else or remove it

alternatively we could model it similar to this:

```rust
enum Unit {
	Wei,
	Ether
        // ...
}

impl Unit {
	pub fn to_wei(&self, value_in_unit: U256) -> U256 {
		match *self {
			Unit::Wei => value_in_unit,
			Unit::Ether => value_in_unit * 1000000000000000000u64.into(),
                        // ...
		}
	}
}

let value = Unit::Ether.to_wei(200.into());
```

would love some feedback

**Comment by tomusdrw** [comment]
Existence of this functions is related to #6 - ethabi doesn't use proper numeric types, so we need to do conversions ourselves.

1. `*_to_wei` is pretty verbose
2. I would avoid trait since it has to be imported.
3. What do you think about:
```rust
sol::Wei::from_ether(5)
```
instead?

**Comment by snd** [comment]
> I would avoid trait since it has to be imported.

which trait are you referring to?

> sol::Wei::from_ether(5)

i like it. it's understandable without additional context which `ether(5)` isn't imho. `sol::unit::ether_to_wei(5)` seems similarly verbose though. maybe `sol::from_ether(5)`? makes clear that it's converting **from** ether and one can guess that it's converting to wei.

**Comment by tomusdrw** [comment]
> which trait are you referring to?

Sorry for some reason I interpreted your enum proposal as trait.

I'd prefer to keep the `wei` and not pollute `sol` interface:
```rust
sol::wei::from_ether(5);
// or 
use std::wei;
wei::from_ether(5);
```

**Comment by snd** [comment]
i really like that. can i go ahead and implement this? are you ok with the `from_*` functions taking a `T: Into<U256>`. then one can pass in byte arrays, u64, etc directly.

**Comment by tomusdrw** [comment]
Sure, go ahead.

**Comment by snd** [comment]
resolved in https://github.com/paritytech/sol-rs/pull/18
