### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by snd** [paritytech/sol-rs#30]
```
error: failed to load source for a dependency on `ethabi`
Caused by:
  Unable to update https://github.com/tomusdrw/ethabi.git#6082addb
```

https://travis-ci.org/paritytech/sol-rs/builds/356872202

can't reproduce locally

any ideas?

**Comment by tomusdrw** [comment]
Seems that a commit is missing, it might have been me breaking it by pushing new changes from `ethabi` mainstream repo. You probably have a copy of the repo locally, could you check the diff and push it?

**Comment by snd** [comment]
thanks! my cargo checkout of the repo had the commit. that's why it was working locally. forced a new checkout and i can now reproduce it.

**Comment by snd** [comment]
fixed the missing commit (https://github.com/paritytech/sol-rs/pull/31). now i'm getting `cannot find trait `Caller` in module `ethabi`` (https://travis-ci.org/paritytech/sol-rs/jobs/359673295#L1182). i see that there are `Call` and `Transact` traits in https://github.com/paritytech/ethabi/pull/85/files. i guess i'll just use that branch
