### ISSUE TITLE
reviewable.io

### ISSUE THREAD

**Issue by snd** [paritytech/sol-rs#32]
i personally find the integration of reviewable.io somewhat annoying.
maybe i don't get its usefulness. happy to learn.
otherwise feel free to remove it.

**Comment by kirushik** [comment]
It was an experiment to see if we can make use of more thorough reviews.
Now (with new options in Github's branch protection: minimal number of reviewers and resetting the review state after pushes into the branch) it's almost definitely useless; disabling it now.
