### ISSUE TITLE
What license does this project use?

### ISSUE THREAD

**Issue by udoprog** [paritytech/sol-rs#35]
Hey!

This project currently does not have a license, meaning it's a bit risky to both use and extend. (No license generally implies proprietary!).

We are doing some work to build a testing framework like sol-rs in [PrimaBlock/parables](https://github.com/PrimaBlock/parables). Most of it is a re-implementation, but we have a handful of things that are copied ([wei.rs](https://github.com/PrimaBlock/parables/blob/master/testing/wei.rs) and the stack management in [trace.rs](https://github.com/PrimaBlock/parables/blob/master/testing/trace.rs#L178)). We want to make sure to give proper attribution. Your project showed that this kind of testing was possible and broke a ton of ground for us.

Could you make sure to add the appropriate license files?

**Comment by snd** [comment]
sol-rs is most likely licensed as GPLv3 (same license as parity itself). @tomusdrw please correct me if i'm mistaken. we'll properly add license information shorty.

**Comment by ddorgan** [comment]
[clabot:test]

**Comment by ddorgan** [comment]
[clabot: check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot: check]
